application: tellingtellingtelling
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: view/stylesheets

- url: /img
  static_dir: view/images

- url: /favicon.ico
  static_files: view/images/favicon.ico
  upload: view/images/favicon.ico

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: ssl
  version: "latest"
